version: "3.5"

services:
  # Scheduler database
  postgres:
    image: postgres:11.5-alpine
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      # Using default "postgres" database and "postgres" user
nn      - POSTGRES_PASSWORD=resaas-dev
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  # postgres admin
  pgadmin:
    image: dpage/pgadmin4:5.4
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
    volumes:
      - ./config/pg-servers.json:/pgadmin4/servers.json
    ports:
      - "81:80"
    depends_on:
      - postgres
  # For async-task message passing
  redis:
    image: redis:6.2-rc2-alpine
    volumes:
      - redis:/data
    ports:
      - 6379:6379
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  celery-worker:
    image: "chainsail-celery-worker:latest"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:resaas-dev@postgres:5432/postgres
      - CHAINSAIL_SCHEDULER_CONFIG=/config/scheduler.yaml
    volumes:
      - ./config:/config
  scheduler:
    image: "chainsail-scheduler:latest"
    volumes:
      - ./config:/config
    ports:
      - "5000:5001"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:resaas-dev@postgres:5432/postgres
      - CHAINSAIL_SCHEDULER_CONFIG=/config/scheduler.yaml
      - GOOGLE_APPLICATION_CREDENTIALS=/config/firebase_service_account.json
    depends_on: [postgres, celery-worker, redis, graphite]
  nginx:
    image: "chainsail-nginx:latest"
    ports:
      - "80:80"
    depends_on:
      - scheduler
  graphite:
    image: "graphiteapp/graphite-statsd"
    restart: "always"
    ports:
      - "8080:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
  client:
    image: "chainsail-client:latest"
    volumes:
      - /home/simeon/projects/resaas/app/client/next.config.js:/opt/app/next.config.js
    ports:
      - "3000:3000"
    environment:
      - GRAPHITE_URL=http://graphite:8080
      - SCHEDULER_URL=http://nginx:80
      - GOOGLE_APPLICATION_CREDENTIALS=/config/client_sa_key.json
    depends_on: [scheduler, graphite, nginx]
volumes:
  redis:
  postgres:
