##############################################################################
# Default values for chainsail chart.
#
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
##############################################################################
# General Settings
##############################################################################
replicaCount: 1

image:
  pullPolicy: IfNotPresent

tolerations:
  # Allow scheduling on "core" service nodes
  - key: 'for_core_services'
    value: 'true'
    effect: 'NoSchedule'

imageHubNamespace: ''
imageTag: 'latest'

##############################################################################
# Scheduler Settings
##############################################################################

# If set, the scheduler will be switched into `dev` mode and assume
# the provided user name for all requests.
schedulerUseDevUser: 'AnonymousDevModeUser'
schedulerNumWorkers: 1
